bot-token: "BOTTOKEN"
server-id: "000000000000000000"

change-nickanme-on-link: false

enable-chatstream: false
chatstream-channel: "000000000000000000"
chatstream-message-format: "§f[§9Discord§f]%USER%: %MESSAGE%"
chatstream-use-permission-groups: false

roles:
  - exampleRole1
  - exampleRole2

exampleRole1:
  role-id: "000000000000000000"
  add-commands:
    - "example command 1"
    - "example command 2"
  remove-commands:
    - "example command 1"
    - "example command 2"

exampleRole2:
  role-id: "000000000000000000"
  add-commands:
    - "example command 1"
    - "example command 2"
  remove-commands:
    - "example command 1"
    - "example command 2"